# Generated by Django 3.0.6 on 2020-06-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200603_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='0', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
