# Generated by Django 3.0.6 on 2020-06-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200604_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(default='0', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(default='0', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(default='0', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
