# Generated by Django 3.0.6 on 2020-06-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200604_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
