# Generated by Django 3.0.6 on 2020-06-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200616_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='api.Genre'),
        ),
    ]
