# Generated by Django 3.0.6 on 2020-07-26 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200616_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
